### ISSUE TITLE
Why the size of the applicationInputBuffers is 4 times the actual size

### ISSUE THREAD

**Issue by Sanath1998** [quic/qidk#11]
HI @quic-shubpate @quic-rneti @quic-ppant 

In yoloNAS example Why the size of the applicationInputBuffers is 4 times the actual size. Input 1228800 (3*320*320*4) instead of  302700 (3*320*320)? 

Please if any proper explanation is there it would really help us.

**Comment by quic-shubpate** [comment]
Hi @Sanath1998 , we have to pass input buffer with Float32 datatype as it is supported by all CPU, GPU and DSP runtime, so each element is 4 bytes in size (buffer_size = no. of elements * size of element)

**Comment by Sanath1998** [comment]
> Hi @Sanath1998 , we have to pass input buffer with Float32 datatype as it is supported by all CPU, GPU and DSP runtime, so each element is 4 bytes in size (buffer_size = no. of elements * size of element)

Can we convert this to original array size as given? If yes what is the procedure @quic-shubpate ?

**Comment by quic-shubpate** [comment]
If you are using SNPE Userbuffer float then each element of the input array should be in Float32 datatype format (if it is not then you can typecast it). SNPE will also generate the output in Float32 datatype format.

This is generally used, as pre-processing on the input buffers needs to be done to change the input range between 0.0 to 1.0 or the range on which the model is trained.

If you are using SNPE Userbuffer TF8 / TF16 then each element of input array should be in UINT8 or UINT16 datatype and SNPE will also generate output in same dtype. (for eg: if model can directly accept camera RGB buffers without any pre-processing)

**Comment by PureHing** [comment]
@quic-shubpate Hi,

I want to ask something, my input is directly the uchar data of NV12, so how should I modify the [ `createUserBuffer`](https://github.com/quic/qidk/blob/870da4b1e0562fe6b914041f48689a52a990af34/Solutions/VisionSolution1-ObjectDetection-YoloNas/app/src/main/cpp/inference_helper.cpp#L118) here?

**Comment by quic-rneti** [comment]
Closing issue, as there is no further question for ~ 2 weeks
