### ISSUE TITLE
 VisionSolution1 problem: snpe-caffe-to-dlc not available anymore!

### ISSUE THREAD

**Issue by cs-jlopezr** [quic/qidk#13]
The new SNPE SDK version does not include the snpe-caffe-to-dlc file. Any plans to update the VisionSolution1 to be able to follow all the steps?

**Comment by quic-rneti** [comment]
This model is based on Caffe model converter and is not supported in latest versions of SDK. We will add a note in the readme saying that it is only applicable for older SDK versions
