### ISSUE TITLE
CUDA dependency in VisionSolution4 (Pose estimation)

### ISSUE THREAD

**Issue by cs-jlopezr** [quic/qidk#14]
Compiling the HDNet-Human-Pose-Estimation model used in the Vision Solution4 assumes that you have CUDA available. Can it be done without CUDA?

**Comment by SahinMjks** [comment]
Hii @cs-jlopezr , In Recent update we've removed the dependency, can you pls try again?

Thanks 
Sahin

**Comment by SahinMjks** [comment]
Hii @cs-jlopezr Please let me know if this solves your issue or not?

Thanks

**Comment by quic-rneti** [comment]
closing issue. Let us know if the issue persists
