### ISSUE TITLE
Vision Solution 2 problems!

### ISSUE THREAD

**Issue by cs-jlopezr** [quic/qidk#15]
After moving to the indicated commit, this command fails: git apply aimet.patch (the file is not available)

**Comment by SahinMjks** [comment]
cd aimet-model-zoo
**_cp -r aimet.patch aimet-model-zoo_** -- Add this in your code.
git apply aimet.patch


![image](https://github.com/quic/qidk/assets/41137255/4ab959da-4edf-4873-aa13-e74cbebcfb3d)

**Comment by SahinMjks** [comment]
Hii @cs-jlopezr Please let me know if this solves your issue or not?

Thanks
