### ISSUE TITLE
where can I find the code implementation of qhci_resize_near？

### ISSUE THREAD

**Issue by PureHing** [quic/qidk#16]
Hi, @quic-rneti 
where can I find the code implementation of qhci_resize_near? Can you provide it? Thank you so much
https://github.com/quic/qidk/blob/870da4b1e0562fe6b914041f48689a52a990af34/QHCI/hvx_cv/sampleApp/main.c#L122

**Comment by quic-rneti** [comment]
Hello @PureHing - source code for qhci_* APIs is not public. You need to be a Qualcomm customer to discuss further details. 

Can you please raise a Salesforce ticket to get more support in this regard. This cannot be supported in open source repositories.
