### ISSUE TITLE
crash on YUV12ToRGB_lastthread

### ISSUE THREAD

**Issue by PureHing** [quic/qidk#17]
When the input and output are both 3840x2160 in size, `YUV12ToRGB_lastthread` function will crash.

**Comment by SahinMjks** [comment]
Hii @PureHing , can you please elaborate for which model you're facing the issue or can you pls share the model link?
Thanks.

**Comment by quic-rneti** [comment]
What is the model you are using ? 
What is the QIDK solution you are referring to ? 
Can you upload artifacts for us to check and get back ?

**Comment by quic-rneti** [comment]
No update from issue reporter for long time, closing issue
