### ISSUE TITLE
Problem with demo application

### ISSUE THREAD

**Issue by Piotr94** [quic/qidk#20]
Recently I have started using Snapdragon Hardware Development Kit. I have followed this course ([link](https://qualcomm.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3ad03740-020a-4a99-a1c8-b07d013b8838)), which was very helpful,  but I met some problems.

My question pertains to using the example application (from[ this link](https://qualcomm.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=524df20e-87e6-4e62-b61c-b07d013b87b1)). When I attempt to run the "Enhancement" application, it works until I click one of the three options: "CPU", "GPU", "DSP" (selecting one of the two images "Sample1.jpg" or "Sample2.jpg" works correctly). At this point, the application shuts down and returns to the previous window. I have attached a recording demonstrating the problem. Do you know what could be causing this issue?

I'll add, in case it would be important, that I'm mirroring device to control it, there are known issues with using mouse ([link](https://estore.lantronix.com/products/snapdragon-8-gen-2-mobile-hardware-development-kit))

https://github.com/quic/qidk/assets/17530823/20971fad-9a98-4262-be7d-ba857aff9210

**Comment by quic-rneti** [comment]
No further comment. QIDK apps are verified on mobile form factor. not tablet form factor. 
and above video looks like user is trying to run apps on Android emulator. So closing this request.
