### ISSUE TITLE
OS version is Debian

### ISSUE THREAD

**Issue by jmiffiko** [quic/qidk#22]
snpe-docker is created with Debian OS whereas Ubuntu 20.04 is expected. snpe-docker returns as follows: 

root@nsato-linux:/workspace# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="
[https://www.debian.org/"](https://www.debian.org/%22)
SUPPORT_URL="
[https://www.debian.org/support"](https://www.debian.org/support%22)
BUG_REPORT_URL="
[https://bugs.debian.org/"](https://bugs.debian.org/%22)

I changed to install python and pip directly, then docker is created with Ubuntu 20.04.

#FROM docker-registry.qualcomm.com/library/ubuntu:20.04
FROM ubuntu:20.04
#FROM docker-registry.qualcomm.com/library/python:3.8

RUN apt update
RUN apt install -y python3.8
RUN apt install -y python3-pip

Moreover, I checked Ubuntu docker from repository is created with Ubuntu 20.04.

nsato@nsato-linux:~$ docker run --name ubuntu_20_04_test -it docker-registry.qualcomm.com/library/ubuntu:20.04
Unable to find image 'docker-registry.qualcomm.com/library/ubuntu:20.04' locally
20.04: Pulling from library/ubuntu
527f5363b98e: Pull complete
Digest: sha256:f8a07ce1ff2eca6446aa5e3cdc727baf5e2e702efde1b68f596e76fca436c171
Status: Downloaded newer image for docker-registry.qualcomm.com/library/ubuntu:20.04
root@ce7118cb0f4f:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="
[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
SUPPORT_URL="
[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
BUG_REPORT_URL="
[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
PRIVACY_POLICY_URL="
[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@ce7118cb0f4f:/#

**Comment by quic-rneti** [comment]
snpe-docker needs update for latest snpe releases. We will update this by first week of July 2024.
