### ISSUE TITLE
Int4 quantization

### ISSUE THREAD

**Issue by Piotr94** [quic/qidk#23]
Hi!

According to the documentation some platforms (for example Snapdragon 8 gen 2) enable using int4 computations. I would like to ask if it is possible to use them through SNPE? If not can you tell me how can I implement int4 quantization on qualcomm platforms?

Kind regards
Piotr

**Comment by quic-rneti** [comment]
Yes - INT4 quantization is possible with SNPE on Snapdragon 8 Gen2, and Snapdragon 8 Gen3. Please follow SDK documentation, and let us know for any specific questions.
