### ISSUE TITLE
snpe-docker build error

### ISSUE THREAD

**Issue by aditya-167** [quic/qidk#24]
Hi,

I am trying to docker build as given in README guide for snpe-docker, however I run through with the following error:
![image](https://github.com/quic/qidk/assets/47297221/0225522e-4ac9-4d2c-8802-1cb55234ca0d). I dont see snpe-docker.tar getting generated (as per the README guide after I docker build). Kindly help me resolve this.

**Comment by quic-rneti** [comment]
Hi - snpe docker needs change for recent AI SDK releases. We will update the snpe-docker by first week of July 2024
