### ISSUE TITLE
QuIC Repolinter errors

### ISSUE THREAD

**Issue by mynameistechno** [quic/qidk#26]
@quic-rneti the check is currently failing. We should correct the violations and/or tweak the config for this particular repo. See the"Repolinter Output" section that is in Error here https://github.com/quic/qidk/actions/runs/9639387487/job/26581482294

For example the `✖ source-license-headers-exist` section is complaining about a lot of source files missing the quic copyright and license header. Can you confirm if QuIC authored all those files? E.g. in the Examples and Solutions directories? If so, we should add the copyright/license headers to those. If they are third party, we should then add an exception to the repolinter config. I can help with this, but here are some instructions

https://github.com/quic/.github?tab=readme-ov-file#customizing-repolinter-rules

**Comment by mynameistechno** [comment]
It looks like the last run is still failing (expand the "Repolinter output" section to see errors about binary files and source files missing the QuIC copyright/license header):
https://github.com/quic/qidk/actions/runs/11051235272/job/30700684960

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/2c11750e-a97d-4971-b589-5d529587b3bd">

What are these binaries and are they necessary to be in the repo? https://github.com/quic/qidk/tree/master/Solutions/NLPSolution3-AutomaticSpeechRecognition-Whisper/Android_App_Whisper/app/src/main/jniLibs/arm64-v8a

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/457f494a-519b-44c7-a278-5b32065564c4">

Are these files all QC-authored? If so, we should add the copyright header. If not we need to exclude paths from repolinter's checks: 

https://github.com/quic/.github?tab=readme-ov-file#customizing-repolinter-rules

**Comment by mynameistechno** [comment]
<img width="619" alt="image" src="https://github.com/user-attachments/assets/e9f25ab0-702b-4a1d-91d5-fad02efaacf9">

The last commit has the failed status run details (the red X). When Repolinter is running without error it'll be a green check. We should only merge PRs when all the checks are passing so the repo is not in a "failed state"

**Comment by quic-vraidu** [comment]
I think Repolinter is not running properly. Copyright details are present for those files.

**Comment by quic-vraidu** [comment]
@mynameistechno, Most of the header files and java files contains the copyright details. Please check why Repolinter script is reporting the issue.

**Comment by mynameistechno** [comment]
> @mynameistechno, Most of the header files and java files contains the copyright details. Please check why Repolinter script is reporting the issue.

The first one I checked doesn't have it:

https://github.com/quic/qidk/blob/master/Solutions/NLPSolution1-QuestionAnswering/scripts/batch_tf_inf.py

> What are these binaries and are they necessary to be in the repo? https://github.com/quic/qidk/tree/master/Solutions/NLPSolution3-AutomaticSpeechRecognition-Whisper/Android_App_Whisper/app/src/main/jniLibs/arm64-v8a

Also what about the binaries? Typically binaries should not be included in a git repo, but in some cases it's valid but we need to alert Repolinter to skip them.

**Comment by quic-vraidu** [comment]
@mynameistechno, Yes, Repolinter reports both valid and invalid files. Can you please solve the issue because even though we correct the invalid files, Repolinter still reports issue for valid files. 

Is it possible validate Repolinter offline before upload to changes to github.

Binaries, I will check and correct them accordingly.

**Comment by mynameistechno** [comment]
> @mynameistechno, Yes, Repolinter reports both valid and invalid files. Can you please solve the issue because even though we correct the invalid files, Repolinter still reports issue for valid files.

@quic-vraidu what do you mean? Please share a file that Repolinter reports as invalid that is valid. This file clearly is missing the QuIC copyright and license:

https://github.com/quic/qidk/blob/master/Solutions/NLPSolution1-QuestionAnswering/scripts/batch_tf_inf.py

That is just one of the files. See the repolinter output at https://github.com/quic/qidk/actions/runs/11164227762/job/31033040264#step:6:471 

for all the violations.

![image](https://github.com/user-attachments/assets/0496b46d-1028-4e96-a702-46adc4c733fe)

> Is it possible validate Repolinter offline before upload to changes to github.

Yes it's possible. You can run it locally, but it also runs when a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) is opened. Your team should be following the GitHub model where changes are proposed as PRs instead of git pushing directly. Repolinter will run as [GitHub Action when a PR is opened](https://github.com/quic/qidk/blob/master/.github/workflows/quic-organization-repolinter.yml#L6). Someone reviews the code and automated checks like unit tests and Repolinter can run prior to merging. See AIMET example: https://github.com/quic/aimet/pull/3352

![image](https://github.com/user-attachments/assets/1edc5abc-0928-4a37-9ee0-a25109a688ff)

You can also run repolinter locally. E.g. with docker

```
docker pull ghcr.io/todogroup/repolinter:v0.11.1
docker run -t -v $PWD:/src -w /src ghcr.io/todogroup/repolinter:v0.11.1 --rulesetUrl https://raw.githubusercontent.com/quic/.github/main/repolint.json
```

**Comment by quic-vraidu** [comment]
@mynameistechno , Repolinter is point to copyrighted files as well. Refer below files. Can you please solve the issue because even though we correct the invalid files, Repolinter still reports issue for valid files. 

I just pointed 3 files. Lot of files have copyright but Repolinter still points as error.
https://github.com/quic/qidk/blob/master/QHCI/hvx_cv/src/base/dsp/qhci_imp.c
https://github.com/quic/qidk/blob/master/QHCI/hvx_cv/src/div16/dsp/div16_imp.c
https://github.com/quic/qidk/blob/master/QHCI/hvx_cv/src/dummy/dsp/dummy_imp.c

**Comment by mynameistechno** [comment]
@quic-vraidu Repolinter is correct. You're not using the license and copyright stipulated per the approval.

**Comment by quic-vraidu** [comment]
@mynameistechno, I followed the suggestion from lost team. You are part the mail chain "Regarding Github QIDK QuIC Repolinter issue" as well.

**Comment by quic-vraidu** [comment]
Changes are merged. Resolved all the repolinter issue according to guidance.
