### ISSUE TITLE
-bash：非法选项 -- p

### ISSUE THREAD

**Issue by na20215** [quic/qidk#3]
source <snpe-sdk-location>/bin/envsetup.sh -t $TENSORFLOW_DIR
about this command.
the -t opt is not exist. 
how does it work?

**Comment by cfasana** [comment]
@na20215 up to my knowledge, it may vary based on the specific version you are using, in the case of SNPE. When you download the SNPE, a _setup.html_ file is usually provided describing the exact procedure that you should follow to set up that specific version of the SDK.

**Comment by na20215** [comment]
> @na20215 up to my knowledge, it may vary based on the specific version you are using, in the case of SNPE. When you download the SNPE, a _setup.html_ file is usually provided describing the exact procedure that you should follow to set up that specific version of the SDK.

ahh, yes ,thanks for your reply , I've already figured out how to configure the environment on my own and completed my task. Still, I appreciate your help; you made me realize that the instruction manual might be in the downloaded package.
