### ISSUE TITLE
Assistance Required for Accessing DETR Notebook Link

### ISSUE THREAD

**Issue by fariverGit** [quic/qidk#30]
The DETR Notebook Link provided in your documentation (https://github.com/quic/qidk/tree/master/Solutions/VisionSolution1-ObjectDetection-DETR) is not accessible via the provided URL (https://github.qualcomm.com/qualcomm-model-zoo-public-mirror/models-for-solutions/tree/main/03-object-detection/detr_resnet101). Could you please look into this matter and provide guidance on how I might access the DETR Notebook? Your prompt response will be greatly appreciated.

**Comment by quic-vraidu** [comment]
Will check and update.

**Comment by quic-rneti** [comment]
Corrected hyperlink to open source link. Pls check now.
