### ISSUE TITLE
NullPointerException in SNPEHelper.loadingMNETSSD()

### ISSUE THREAD

**Issue by janeSmith99221** [quic/qidk#31]
I am encountering a FATAL EXCEPTION in the ObjectDetection-YoloNas application, specifically in the SNPEHelper.loadingMNETSSD() method. The error message is as follows:
```
CopyFATAL EXCEPTION: Thread-4 (Ask Gemini)
Process: com.qc.objectdetection, PID: 12255
java.lang.NullPointerException: Attempt to invoke interface method 'com.qualcomm.qti.snpe.FloatTensor com.qualcomm.qti.snpe.NeuralNetwork.createFloatTensor(int[])' on a null object reference
    at com.qc.objectdetection.SNPEHelper.loadingMNETSSD(SNPEHelper.java:97)
    at com.qc.objectdetection.CameraFragment$7.run(CameraFragment.java:1109)
```
This error is occurring when I try to run the ObjectDetection-YoloNas application on my device. Based on the stack trace, it seems that the NeuralNetwork object is null when the createFloatTensor() method is called.

**Comment by quic-vraidu** [comment]
Can I know know the snpe version you are using?

**Comment by quic-rneti** [comment]
All applications are updated with latest SDK version. Pls check and get back once
