### ISSUE TITLE
Unable to import com.qualcomm.qti.snpe.* classes in SuperResolution class

### ISSUE THREAD

**Issue by janeSmith99221** [quic/qidk#32]
I'm working on the ImageSuperResolution application, and I'm facing an issue when trying to import the following classes in the SuperResolution class:
```
javaCopyimport com.qualcomm.qti.snpe.FloatTensor;
import com.qualcomm.qti.snpe.NeuralNetwork;
import com.qualcomm.qti.snpe.SNPE;
```
The IDE (Android Studio) is not able to resolve these classes, and I'm getting an error stating that the classes cannot be found.

**Comment by quic-vraidu** [comment]
Can I know know the snpe version you are using?

**Comment by quic-rneti** [comment]
All applications are updated to latest SDK version, and published to github. Pls check once
