### ISSUE TITLE
Not supported PySNPE for ubuntu aarch64

### ISSUE THREAD

**Issue by developer-vbee** [quic/qidk#34]
i install pysnpe-utils in my ubuntu aarch64 machine, but faced the error when run this line
```python
try:
    from qti.aisw.dlc_utils import snpe_dlc_utils
    from qti.aisw.dlc_utils import modeltools
except ImportError as ie:
    logger.error("Failed to find necessary package:")
    logger.error(str(ie))
    logger.error("Please ensure that $SNPE_ROOT/lib/python is in your PYTHONPATH")
``` 

Through the stacktrace i found that in the SNPE SDK, the dlc_utils has only *.so file for linux-x86_64, windows-arm64ec, windows-x86_64. So can I run pysnpe in ubuntu-aarch64, or pysnpe doesn't support it for now?
![image](https://github.com/user-attachments/assets/209e3de0-ff88-47c5-988b-5ea0ed50df8e)

**Comment by quic-vraidu** [comment]
Can I know which laptop or PC you are using which contains ubuntu arm OS?

**Comment by developer-vbee** [comment]
I am using the AI Box that includes Qualcomm hardware. You can find that here [https://hsptek.com/vi/san-pham/ai-box-6490/](url)

**Comment by quic-rneti** [comment]
Dear user - May I know, for which purpose you are trying to use PySNPE ? 
Are you trying to use the Python API for model preparation or Model deployment (on streaming video, streaming camera data)

**Comment by developer-vbee** [comment]
Thank for quickly reply @quic-rneti. I want to use PySNPE for model deployment, since I already can do the model conversion step in a x86_64 machine. But I have to deploy the dlc model in this ai-box that has ubuntu-arm OS.

**Comment by developer-vbee** [comment]
If PySNPE doesn't support ubuntu-arm yet, can you suggest other options for model deployment @quic-rneti? Thank you.

**Comment by quic-rneti** [comment]
Please refer to this : https://github.com/quic/qidk/tree/master/Tools/snpe-helper

We deployed this for Windows on Snapdragon, LNX.LE (Embedded Linux), and LNX.LU (Ubuntu Linux) for multiple customers. Do check it out, and let us know
