### ISSUE TITLE
Run cpu successfully and not in GPU and DSP

### ISSUE THREAD

**Issue by zengjie617789** [quic/qidk#35]
I used a app to load a library from cpp, and it succeed. While run it on GPU or DSP mode, it raise an error below:
![image](https://github.com/user-attachments/assets/64675363-a823-4ade-809c-b40d92b0c9e1)

**Comment by quic-vraidu** [comment]
1. Can you please provide details on application in which error is found? 
2. Are you trying example solutions provided in QIDK github?
3. Are you trying with latest snpe sdk 2.25 version?

**Comment by zengjie617789** [comment]
thanks for you instant response firstly.
1.  I use the code to initial snpe builder below:
    
   ```
 snpe = setBuilderOptions(container, runtime, runtimeList,
                             useUserSuppliedBuffers, platformConfig,
                             usingInitCaching, cpuFixedPointMode,
                             outputLayerNames);
```
which load container successfully while snpe returned a nullptr when runtime is gpu or dsp;
2. I did my best try to run the objectdetectionYoloNas projects, unfortunatelly I meet much error when I run it;
3. The snpe version is updated to the latest version 2.26 and I donot think the version matters because it runs well when in cpu mode.
thanks for any advice in advance.

**Comment by quic-vraidu** [comment]
QIDK repo is validated recently with SNPE 2.25 and all solutions are working fine. I would recommended to use 2.25 version, follow the steps in Readme and Notebook, re-confirm the libraries are copied properly. 

If you still have issues, let us know.

**Comment by quic-rneti** [comment]
This error looks like HTP backend libraries are not properly pushed to device. You need to push proper libraries : Pls check here once https://mysupport.qualcomm.com/supportforums/s/feed/0D5dK000001fGzWSAU
