### ISSUE TITLE
YOLOv8 quantized not running on DSP or GPU Runtime

### ISSUE THREAD

**Issue by muhammad-qasim-cowlar** [quic/qidk#36]
SDK Version: 2.26
I can successfully execute snpe-net-run on my cpu and gpu on the unquantized model. I am following all the steps in this repository and I identified two layers to add to the .encodings file however when using this quantized model on dsp I get the following output:
```
snpe-net-run --container yolo_quantized.dlc --input_list list.txt --output_dir $OUTPUT_FOLDER --use_dsp --debug    
error_code=1002; error_message=Layer parameter value is invalid. No backend could validate Op=/model.22/Sigmoid_1 Type=ElementWiseNeuron error code=3110; error_component=Model Validation; line_no=142; thread_id=546085487872

```
The device I am using is sm8250 with v66 DSP arch. I have no idea what is causing this error.

**Comment by quic-vraidu** [comment]
QIDK project is validated with SM8550 and SM8650. I recommended to use these devices.

**Comment by quic-rneti** [comment]
SM8250 is a previous generation of device, which has a different DSP accelerator. It is called HTA (Hexagon Tensor Accelerator)
Current generation chipsets have a newer hardware blocks - If you want to use SM8250, and it's variants (RB5), please try running models with GPU runtime, and post questions here : https://mysupport.qualcomm.com/supportforums/s/

Closing this request.
