### ISSUE TITLE
The accuracy results of the Inception_V3 quantized model running on the QCS6490 DSP were unexpected.

### ISSUE THREAD

**Issue by HuiJu1218** [quic/qidk#38]
Hi, 
I used the sample from [this link](https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/tutorial_inceptionv3.html) and followed the tutorial script to download and quantize the model. When running the quantized model on the QCS6490, The accuracy drop much higher than expected. Below are the SDK version and SOP I used. I'd like to know if this is an issue, and how I can resolve it.
- SNPE SDK version: 2.22.6.240515
- model: inception v3

My workflow from model quantization on host and deployment to OCS6490 is as follows.
1. Download inception v3 pb model.
2. export TENSORFLOW_HOME
3. quantize model and get DLC 
    ```
   python3 $SNPE_ROOT/examples/Models/InceptionV3/scripts/setup_inceptionv3_snpe.py -a ~/tmpdir -d -r dsp
   ```
4. Run quantized model on QCS6490's DSP
   ```
    snpe-net-run --container dlc/inception_v3_quantized.dlc --input_list data/cropped/raw_list.txt --use_dsp
   ```
5. Use python script `show_inceptionv3_classifications_snpe.py` to check output

What I observed is that there are recognition results, but for the 1000 ImageNet classes, only fewer than 20 have any recognition results. As shown in the following image, the top recognition results are all 0.0.
![螢幕擷取畫面 2024-10-03 161759](https://github.com/user-attachments/assets/1a3e472d-e632-460f-8334-09291279cfdd)

Thanks.

**Comment by quic-vraidu** [comment]
Refer Model-Accuracy-Mixed-Precision. This should help you with the process.
