### ISSUE TITLE
No bin/aarch64-android/* staff in QNN 2.13 Windows Build

### ISSUE THREAD

**Issue by lx200916** [quic/qidk#4]
I installed `Qualcomm AI Engine Direct` 2.13 Windows version with QPM, but fail to find binaries to run network on Android Devices. There is nothing like `bin/aarch64-android/qnn-net-run` or any other things, and in fact there is only binaries for Windows or x86 Linux located in the `bin` folder.

How Can I test my model on a real Android Device?

**Comment by quic-rneti** [comment]
Hello - to use Qualcomm AI Engine Direct on Android, you need to download the Linux variant. Not Windows Variant. Windows variant will work for Windows on Snapdragon Hardware. Not, Windows as a development platform. Please note this.
