### ISSUE TITLE
Quant_YoloNas_s_320.dlc model not working .

### ISSUE THREAD

**Issue by Arya-Ayra** [quic/qidk#45]
Can I get a pre-built Quant_YoloNas_s_320.dlc model to test on the app. The model I built does not create bounding boxes or has no detection on the app. A link to a working Quant_YoloNas_s_320.dlc will be appreciated.
Thank you.

**Comment by Arya-Ayra** [comment]
I think tnhe issue I am facing is not because of the Model, but because of the Model Loading process in the code file: ObjectdetectionYoloNas.cpp.
The logs I get are:
 I  Reading SNPE DLC ........................................................
E  Failed to load ASSET, needed to load DLC.

Code responsible to log the error:
```
    LOGI("Reading SNPE DLC ........................................................");
    std::string result;

    AAssetManager* mgr = AAssetManager_fromJava(env, asset_manager);
    AAsset* asset_BB = AAssetManager_open(mgr, "Quant_yoloNas_s_320.dlc", AASSET_MODE_UNKNOWN);
    if (NULL == asset_BB) {
        LOGE("Failed to load ASSET, needed to load DLC\n");
        result = "Failed to load ASSET, needed to load DLC\n";
        return env->NewStringUTF(result.c_str());
    }
```

Any help regarding this will be useful. Any better logging technique that can help me know the issue better.

**Comment by quic-vraidu** [comment]
@Arya-Ayra, You need to copy the dlc file to assets folder. Please check the steps.
app\src\main\assets : Contains Model binary DLC

**Comment by Arya-Ayra** [comment]
Thank you for the quick resolution.
