### ISSUE TITLE
Issue while building project 

### ISSUE THREAD

**Issue by ARK3105** [quic/qidk#46]
For VisionSolution1-ObjectDetection-YoloNas : 

Multiple build operations failed.
    Could not create task ':app:processDebugResources'.
    Could not create task ':sdk:generateDebugRFile'.
Could not create task ':app:processDebugResources'.
Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

**Comment by quic-vraidu** [comment]
We are observing compilation issues with latest Android studio 2024. 
Please try to use Android studio 2021 version i.e this is version i use Android Studio Dolphin | 2021.3.1 Patch 1
