### ISSUE TITLE
yolo nas w8a8???

### ISSUE THREAD

**Issue by suhyun01150** [quic/qidk#52]
Hello, I am following the instructions on [this GitHub page](https://github.com/quic/qidk/blob/master/Solutions/VisionSolution1-ObjectDetection-YoloNas/GenerateDLC.ipynb). While running the GenerateDLC.ipynb, I encountered an error at the last step:
snpe-dlc-graph-prepare --input_dlc models/yolo_nas_w8a8.dlc --set_output_tensors=877,885 --htp_socs=sm8550 --output_dlc=models/Quant_yoloNas_s_320.dlc
[ERROR] DLC file models/yolo_nas_w8a8.dlc doesn't exist!

Where should I create the yolo_nas_w8a8.dlc file?
did you mean "Quant_intermediate_yoloNas_s_320.dlc"?

**Comment by quic-vraidu** [comment]
Yes, in snpe-dlc-graph-prepare input dlc should be Quant_intermediate_yoloNas_s_320.dlc
