### ISSUE TITLE
Attempting to run the QNN Vision YoloNas solution but cant seem to find some of the c++ source and hpp files

### ISSUE THREAD

**Issue by sankalpkallakuri** [quic/qidk#57]
The following files I could not locate in the qairt SDK or in the Github repo

include/QnnTypeMacros.hpp src/QnnWrapperUtils.cpp Utils/DataUtil.cpp Log/Logger.cpp Log/LogUtils.cpp PAL/src/common/GetOpt.cpp PAL/src/common/StringOp.cpp PAL/src/linux/Directory.cpp PAL/src/linux/DynamicLoading.cpp PAL/src/linux/FileOp.cpp PAL/src/linux/Path.cpp Utils/DynamicLoadUtil.cpp Utils/IOTensor.cpp Utils/QnnSampleAppUtils.cpp Utils/DynamicLoadUtil.cpp
        Log/Logger.cpp
        
 These files are listed in the cmakelists.txt , but i cant seem to find them anywhere. Please guide.

**Comment by quic-vraidu** [comment]
Check the step #2  in Build APK file with Android Studio

**Comment by sankalpkallakuri** [comment]
i ran resolvedependencies.sh in the solutions folder and the files appeared.
