### ISSUE TITLE
VisionSolution4-PoseEstimation： How to do post-processing

### ISSUE THREAD

**Issue by Tom-plus** [quic/qidk#8]
According to the tutorial, I have converted yolo_nas_s.onnx into DLC and quantified it. Then, I deduced the final DLC and obtained two outputs, one with shape of (1, 2100 80) and other with the shape of (1, 2100, 4) which I assume the shapes of scores and boxes respectively.
My question is regarding processing these outputs. I cannot understand the Java and C++code in the tutorial. Is there a Python related tutorial available？

**Comment by Tom-plus** [comment]
Now that I have done the post-processing for YOLO, how should I do the post-processing for HRNET?

**Comment by quic-rneti** [comment]
We already have pre/post for YoloNAS, and HRNET in the application in C++. Are you looking for python pre/post ?

**Comment by quic-rneti** [comment]
Python pre/post for YoloNAS available here - 
https://github.com/quic/ai-stack-models/tree/main/models-for-solutions/03-object-detection/yolonas

For HRNet, we have it internally, but did not public to public repository, yet.

**Comment by quic-rneti** [comment]
Closing, as there is no further update
