### ISSUE TITLE
undefined reference to `Snpe_TensorShape_Set'

### ISSUE THREAD

**Issue by Sanath1998** [quic/qidk#9]
Hi @quic-rneti, @quic-shubpate , @quic-ppant , I was able to sync the gradle successfully and while building the projectw as getting the below error.

 **CMakeFiles/objectdetectionYoloNas.dir/inference_helper.cpp.o:(.debug_info+0x3246): undefined reference to `Snpe_TensorShape_Set'
  CMakeFiles/objectdetectionYoloNas.dir/objectdetectionYoloNas.cpp.o:(.debug_info+0x1f6c7): undefined reference to `Snpe_TensorShape_Set'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.**

Is there any thing which I want to do from my end. I have even checked the CMakeLists.txt inside VisionSolution1-ObjectDetection-YoloNas\app\src\main\cpp\ path and all its correct. 

If possible could you please help out on this?

**Comment by quic-shubpate** [comment]
Hi @Sanath1998 ,
Please ensure that you are pushing libSNPE.so from Linux variant of SNPE SDK into the jniLibs directory.

On qpm.qualcomm.com, there will be SNPE SDK for Windows and Linux. Since we are developing for Android, so you have to download the Linux variant of SNPE SDK and use the libraries from it.

You can also confirm whether symbol is present in libSNPE.so using the **nm** command.

**Comment by Sanath1998** [comment]
Is there any link from where I can download SNPE SDK? IF yes, that would have been very helpful for us.

Actually one thing what I want to say is, android application I'm running is on windows machine, so SNPE SDK of Linux Variant will support windows environment machine uh?

**Comment by quic-ppant** [comment]
Hi,

You can download it from this link https://qpm.qualcomm.com/#/main/tools/find
Search for Qualcomm ai and then click on drop down "Qualcomm@ AI stack" after that click on “Qualcomm Neural processing sdk”. This is the snpe sdk.
For windows you can install directly and for linux the procedure can be found after you click on the sdk.
Once you are able to extract the sdk. Please, check sdk documentation for setup. 

For android please use linux variant of sdk.

**Comment by Sanath1998** [comment]
Hi @quic-rneti @quic-shubpate @quic-ppant 
we have followed 

https://github.com/quic/qidk/blob/master/Solutions/VisionSolution1-ObjectDetection-YoloNas/resolveDependencies.sh
to resolve dependencies and make sure to follow the above link.

SNPE version we have build in linux environment and the SNPE version is 2.10.0.4541

**Comment by quic-rneti** [comment]
Sample documentation path for Windows SDK : C:\Qualcomm\AIStack\SNPE\2.19.0.240124\docs\SNPE\html\index.html 

SDK_ROOT would be C:\Qualcomm\AIStack\SNPE\2.19.0.240124\ 
Similarly in Linux. It is always recommended to use the latest SDK version.

**Comment by Sanath1998** [comment]
Hi @quic-rneti @quic-shubpate @quic-ppant, sorry to ask one thing.

Actually we want to replicate same as https://github.com/quic/qidk/tree/master/Solutions/VisionSolution1-ObjectDetection-YoloNas
as given above. But we are getting some errors in the android applications which is leading us for errors.

Errors:-
=======
![image](https://github.com/quic/qidk/assets/40652653/564a425e-aedc-4ab7-b2d9-f1a686170a77)
What is the issue for this errors. Actually we have followed all the steps mentioned in the Resolvdependencies.sh file.

And  do we have to change any CmakeLists.txt to link any files? Because undefined reference comes when files are not properly interlinked. Please if any resolution is there it would be very helpful.
